blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/saulsharma/voltra/discussions
    about: Use this section to ask questions and discuss topics that are not related to bug reports or feature requests.
